image: gitpod/workspace-full

vscode:
  extensions:
    - streetsidesoftware.code-spell-checker

tasks:
  - init: bundle install
    command: 

tasks:
  - name: Setup
    init: bundle install
    command: bundle exec jekyll serve --watch --drafts

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-browser
    visibility: public
