# Welcome to Jekyll!
# Where things are
source:      .
destination: ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Site settings
title: Andrea Falzetti
email: andrea@falzetti.me
header-img: img/home-bg.jpg
description: Software Engineer, London
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andreafalzetti.github.io" # the base hostname & protocol for your site
twitter_username: rexromae
facebook_username:  rexromae
github_username:  andreafalzetti
copyright_name: Andrea Falzetti

# Build settings
markdown: kramdown

include: ['_pages']

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ["less","node_modules","Gruntfile.js","package.json","README.md"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
paginate: 10
gems:         [jekyll-paginate, jekyll-feed, jekyll-gist]
